### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by cdpritcha** [petetnt/brackets-name-a-project#6]
Great extension. Solves my overall project naming issue. One small problem-- if I choose a color that is dark, I can't read the text. An option to make the text color either black or white would be great. Or, if it is easier, an option to set the text color just like the background would be fine too.

**Comment by petetnt** [comment]
Yep, great idea :+1: I'll implement this later this week together with #5

**Comment by mwvd** [comment]
:+1:

**Comment by jedelwey** [comment]
Yes, big feature to add:+1:

**Comment by petetnt** [comment]
Added in 0.0.5. Thanks for your contribution :+1:
