### ISSUE TITLE
Add option change font color

### ISSUE THREAD

**Issue by jedelwey** [petetnt/brackets-name-a-project#7]
Hello, I have  a dark theme and if I try to open a proyect in yellow the font color is white and this its a nod good combination.

My theme is Monokai for if you try to replicate the problem. And coming soon y try to make a pull request or add a spanish translation of `name-a-project`.

**Comment by petetnt** [comment]
I'll try to do this asap, this is similar to #6 so I am closing this

**Comment by jedelwey** [comment]
Ok no problem. Sorry for duplicate

**Comment by petetnt** [comment]
Added in 0.0.5. Thanks for your contribution :+1:
